config/routes.rb
Rails.application.routes.draw do

  get 'stats/counts' => 'stats#counts'
  get 'stats/statistiken' => 'stats#statistics'

  post 'subscriptions/create'
  delete 'subscriptions/destroy'
  get 'subscription/confirm/:confirmation_token' => 'subscriptions#confirm', as: 'subscriptions_confirm'
  get 'subscription/unsubscribe/:item_type/:unsubscribe_token' => 'subscriptions#destroy', as: 'subscriptions_unsubscribe'
  delete 'subscription/unsubscribe' => 'subscriptions#unsubscribe_user', as: 'subscriptions_unsubscribe_user'

  get 'users/items'

  get 'reactivate/:token' => 'item_reactivation#reactivate', as: 'reactivate'

  get 'welcome/index'
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => {confirmations: 'confirmations'}

  resources :offers do
    member do
      put :toggle_active
    end
  end

  resources :requests do
    member do
      put :toggle_active
    end
  end

  resources :answers, only: [:create]

  # Error handling
  get '/404' => redirect('/errors/404')
  get '/422' => redirect('/errors/422')
  get '/500' => redirect('/errors/500')
  get '/errors/:error_code', to: 'errors#error'

  root to: 'welcome#index'
end

app/models/request.rb
class Request < ApplicationRecord
  include Item

  validates_presence_of :title, :description, :gender
  validates_length_of :title, maximum: 140

  enum gender: { dontcare: 0, female: 1, male: 2 }
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_editable_request, only: [:edit, :update, :destroy, :toggle_active]

  def index
    @requests = Request.visible_for(current_user, Request).order(Arel.sql('from_date IS NOT NULL, from_date ASC'), updated_at: :desc).includes(:user)
  end

  def show
    @request = Request.visible_for(current_user, Request).find_by(id: params[:id]) or (authenticate_user! and redirect_to requests_path)
  end

  def new
    @request = Request.new
  end

  def edit
  end

  def create
    @request = Request.new(request_params)
    @request.user = current_user

    if @request.save
      flash = {}
      if current_user.unlocked
        flash[:notice] = tm 'helpers.creation_success', @request
        Subscription.requests.confirmed.each do |subscriber|
          SubscriptionMailer.new_item_notification(@request, subscriber).deliver_now
        end
      else
        flash[:alert] = tm 'helpers.creation_success_unlock_required', @request
        User.admin.find_each do |admin|
          UserMailer.admin_notice_mail(@request, admin).deliver_now
        end
      end
      redirect_to @request, flash: flash
    else
      render action: 'new'
    end
  end

  def update
    if @request.update(request_params)
      redirect_to @request, notice: tm('helpers.update_success', @request)
    else
      render action: 'edit'
    end
  end

  def destroy
    @request.destroy
    redirect_to requests_url
  end

  def toggle_active
    if @request.toggle!(:is_public)
      if @request.is_public?
        notice = tm('helpers.make_public_success', @request)
      else
        notice = tm('helpers.hide_success', @request)
      end
      redirect_to @request, notice: notice
    else
      render action: 'show'
    end
  end

  private
    def set_editable_request
      @request = current_user.requests.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params[:request].permit(:title, :description, :from_date, :to_date, :gender)
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
  def from_date_info request
    if request.from_date && !request.from_date.past?
      "#{t 'requests.show.from'} #{l request.from_date}"
    else
      t 'requests.show.now'
    end
  end
end

app/views/requests/_form.html.erb
<%= custom_bootstrap_form_for @request do |f| %>
    <div class="edit">

      <div class="row">
        <%= f.text_area :title,
                         input_group_wrapper_class: 'input-group-lg col-md-12',
                         wrapper_class: 'title',
                         class: 'short-description',
                         append: (@request.title ? 140 - @request.title.length : 140).to_s,
                         placeholder: tm('items.placeholder.title', Request),
                         hide_label: true %>
      </div>

      <hr/>

      <div class="row">
        <div class="col-md-8">
          <%= f.text_area :description, wrapper_class: 'description', hide_label: true, placeholder: t('items.placeholder.description'), help: ('<span class="warning"><i class="fa fa-shield"></i> ' + tm('privacy.warning', Request, count: 2) + '</span>').html_safe %>
        </div>

        <div class="col-md-4">
          <div class="info">
            <div class="btn-group input-group input-group-sm gender">
              <span class="input-group-addon"><%= t('requests.help.gender_selection') %></span>
              <%= gender_select @request.gender %>
              <%= f.hidden_field :gender %>
            </div>
            <%= f.localized_text_field :from_date,
                                       'data-behaviour' => 'datepicker',
                                       input_group_wrapper_class: 'input-group-sm',
                                       prepend: t('activerecord.attributes.request.from_date'),
                                       hide_label: true %>
            <%= f.localized_text_field :to_date,
                                       'data-behaviour' => 'datepicker',
                                       input_group_wrapper_class: 'input-group-sm',
                                       prepend: t('activerecord.attributes.request.to_date'),
                                       placeholder: t('items.placeholder.temporal'),
                                       hide_label: true %>
          </div>
        </div>
      </div>

      <hr/>

      <div class="row">
        <div class="col-md-1 explanation">
          <i class="fa fa-info icon"></i>
        </div>
        <div class="col-md-11">
          <%= tm 'privacy.explanation', @request %>
        </div>
      </div>

      <hr/>

      <div class="row">
        <div class="col-md-12">
          <div class="form-actions">
            <%= f.submit nil, class: 'btn btn-primary' %>
            <%= link_to t('helpers.links.cancel'), requests_path, class: 'btn btn-default' %>
          </div>
        </div>

      </div>
    </div>

<% end %>

app/views/requests/_list.html.erb
<% if requests.count == 0 %>
  <div>
    <%= t 'requests.list.none' %>
  </div>
<% end %>
<% requests.each do |request| %>
<fieldset class="item">
  <%= badges_for request %>

  <div class="title">
    <strong><%= link_to request.title, request %></strong>
  </div>

  <table class="request-specifics">
    <tbody>
    <tr>
      <td class="gender">
        <%= gender_icon request.gender %>
      </td>
      <td class="time">
        <%= from_date_info request %>
      </td>
      <% if request.to_date %>
        <td class="time">
          <%=t 'requests.show.to' %> <%=l request.to_date %>
        </td>
      <% end %>
    </tr>
    </tbody>
  </table>

  <div class="description">
    <div class="short transition"></div>
    <div class="long transition"><%= auto_link simple_format(request.description) %></div>
  </div>

  <div class="contact">
    <div class="inline-button toggle-collapse">
      <div class="short"><%= t 'helpers.more' %>&#x25BC;</div>
      <div class="long"><%= t 'helpers.less' %>&#x25B2;</div>
    </div>

    <div class="inline-button answer">
      <%= link_to request do %>
        <%= t("helpers.#{current_user == request.user ? 'show' : 'answer'}") %>
      <% end %>
    </div>
    <span>&nbsp;|&nbsp;<%= t("requests.show.user", name: request.user.name) %></span>
  </div>
</fieldset>
<% end %>

app/views/requests/edit.html.erb
<div class="page-header">
  <h1><%=t '.title' %></h1>
</div>
<%= render partial: 'form' %>

app/views/requests/index.html.erb
<%= render partial: 'shared/list_page_header', locals: { count: @requests.count, item: 'request', header_class: 'page-header'} %>
<div class="row">
  <div class="sort">
    <%= render partial: 'list', locals: {requests: @requests} %>
  </div>
</div>

app/views/requests/new.html.erb
<div class="page-header">
  <h1><%=t '.title' %></h1>
</div>
<%= render partial: 'form' %>

app/views/requests/show.html.erb
<div class="page-header">
  <h1>
    <% if @request.user == current_user %>
      <%=t '.title.mine' %>
    <% else %>
      <%=t '.title.other', name: @request.user.name %>
    <% end %>
    <% if current_user&.admin? %>
      <% unless @request.user.unlocked? %>
        <%= link_to t('users.lock.unlock'), unlock_admin_user_path(@request.user), method: :put, class: 'btn btn-default' %>
      <% end %>
    <% end %>
  </h1>
</div>

<div class="item">

  <%= badges_for @request %>
  <div class="title"><strong><%= @request.title %></strong></div>

  <div class="until">
    <table class="request-specifics">
      <tbody>
      <tr>
        <td class="gender">
          <%= gender_icon @request.gender %>
        </td>
        <td class="time">
          <%= from_date_info @request %>
        </td>
        <% if @request.to_date %>
          <td class="time">
            <%=t '.to' %> <%=l @request.to_date %>
          </td>
        <% end %>
      </tr>
      </tbody>
    </table>
  </div>

  <div class="description">
    <%= auto_link simple_format(@request.description) %>
  </div>

  <% if current_user != @request.user %>
    <%= render 'answers/form', answer: @answer ||= @request.answers.build %>
  <% else %>
    <h2><i class="fa fa-comments-o"></i> <%= t 'answers.title' %></h2>
    <% if @request.answers.count > 0 %>
      <%= render @request.answers %>
    <% else %>
      <h4><%= t 'answers.none' %></h4>
    <% end %>
  <% end %>

</div>

<hr />

<div class="form-actions">
  <%= link_to t('helpers.links.back'), requests_path, class: 'btn btn-default'  %>
  <% if current_user == @request.user %>
    <% if @request.outdated? %>
      <%= link_to t('items.reactivate'), reactivate_path(@request.get_or_create_reactivator.token), class: 'btn btn-primary' %>
    <% end %>
    <%= link_to t('helpers.links.edit'), edit_request_path(@request), class: 'btn btn-default' %>
    <% if @request.is_public? %>
      <%= link_to '<i class="fa fa-eye-slash"></i> '.html_safe + t('helpers.links.hide'), toggle_active_request_path(@request), method: :put, class: 'btn btn-default' %>
    <% else %>
      <%= link_to '<i class="fa fa-eye"></i> '.html_safe + t('helpers.links.make_public'), toggle_active_request_path(@request), method: :put, class: 'btn btn-default' %>
    <% end %>
    <%= link_to t('helpers.links.destroy'),
                request_path(@request),
                method: 'delete',
                data: { confirm: t('helpers.links.confirm') },
                class: 'btn btn-danger' %>
  <% end %>
</div>