config/routes.rb
Rails.application.routes.draw do

  get 'stats/counts' => 'stats#counts'
  get 'stats/statistiken' => 'stats#statistics'

  post 'subscriptions/create'
  delete 'subscriptions/destroy'
  get 'subscription/confirm/:confirmation_token' => 'subscriptions#confirm', as: 'subscriptions_confirm'
  get 'subscription/unsubscribe/:item_type/:unsubscribe_token' => 'subscriptions#destroy', as: 'subscriptions_unsubscribe'
  delete 'subscription/unsubscribe' => 'subscriptions#unsubscribe_user', as: 'subscriptions_unsubscribe_user'

  get 'users/items'

  get 'reactivate/:token' => 'item_reactivation#reactivate', as: 'reactivate'

  get 'welcome/index'
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => {confirmations: 'confirmations'}

  resources :offers do
    member do
      put :toggle_active
    end
  end

  resources :requests do
    member do
      put :toggle_active
    end
  end

  resources :answers, only: [:create]

  # Error handling
  get '/404' => redirect('/errors/404')
  get '/422' => redirect('/errors/422')
  get '/500' => redirect('/errors/500')
  get '/errors/:error_code', to: 'errors#error'

  root to: 'welcome#index'
end

app/models/subscription.rb
class Subscription < ApplicationRecord

  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/ }
  validates :confirmation_token, uniqueness: { allow_blank: true, allow_nil: true }
  validates :unsubscribe_token, uniqueness: true

  before_validation :generate_tokens!, on: :create

  scope :confirmed, -> { where(confirmation_token: [nil, '']) }
  scope :offers, -> { where(offers: true) }
  scope :requests, -> { where(requests: true) }

  def generate_tokens!
    self.confirmation_token = loop do
      random_token = SecureRandom.urlsafe_base64(nil, false)
      Subscription.exists?(confirmation_token: random_token) or break random_token
    end
    self.unsubscribe_token = loop do
      random_token = SecureRandom.urlsafe_base64(nil, false)
      Subscription.exists?(unsubscribe_token: random_token) or break random_token
    end
  end

  def confirmed?
    confirmation_token.blank?
  end

  def confirm!
    update!(confirmation_token: nil)
  end

  def subscribed_types
    return 'all' if offers? && requests?
    return 'requests' if requests?
    return 'offers' if offers?
    nil
  end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

  before_action :check_offers_or_requests, only: [:create]
  before_action :authenticate_user!, only: [:unsubscribe_user]

  def create
    @subscription = Subscription.find_or_create_by(email: subscription_params[:email])
    @subscription.offers = true if subscription_params[:offers] == 'true'
    @subscription.requests = true if subscription_params[:requests] == 'true'
    if @subscription.changed?
      unless @subscription.save
        redirect_back(fallback_location: root_path, flash: { error: t('subscriptions.subscribe.error_save') + ' ' + @subscription.errors.full_messages.join('. ') + '.'})
        return
      end
      if @subscription.confirmed?
        SubscriptionMailer.subscribe_notification(@subscription).deliver_now unless user_signed_in?
        redirect_back(fallback_location: root_path, notice: t('subscriptions.subscribe.success.confirmed'))
        return
      end
    end
    if user_signed_in? && current_user.email == @subscription.email
      if current_user.confirmed?
        @subscription.confirm!
        redirect_back(fallback_location: root_path)
      else
        redirect_back(fallback_location: root_path, notice: t('subscriptions.subscribe.success.unconfirmed_user'))
      end
    elsif @subscription.confirmed?
      redirect_back(fallback_location: root_path, flash: { error: t('subscriptions.subscribe.error_existing')})
    else
      SubscriptionMailer.confirmation_request(@subscription).deliver_now
      redirect_back(fallback_location: root_path, notice: t('subscriptions.subscribe.success.unconfirmed'))
    end
  end

  def unsubscribe_user
    @subscription = Subscription.find_by_email(current_user.email)
    unless @subscription
      redirect_back(fallback_location: root_path, flash: { error: t('subscriptions.unsubscribe.not_subscribed')})
      return
    end
    @subscription.offers = false if subscription_params[:offers] == 'true'
    @subscription.requests = false if subscription_params[:requests] == 'true'
    if @subscription.offers || @subscription.requests
      @subscription.save! if @subscription.changed?
    else
      @subscription.destroy
    end
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @subscription = Subscription.find_by_unsubscribe_token(params[:unsubscribe_token])
    unless @subscription
      redirect_to root_path, flash: { error: t('subscriptions.unsubscribe.bad_token')}
      return
    end
    case params[:item_type]
      when 'offers'
        @subscription.offers = false
      when 'requests'
        @subscription.requests = false
      when 'all'
        @subscription.offers = false
        @subscription.requests = false
      else
        redirect_to root_path, flash: { error: t('subscriptions.unsubscribe.bad_item_type')}
        return
    end
    if @subscription.offers || @subscription.requests
      @subscription.save! if @subscription.changed?
    else
      @subscription.destroy
    end
    unless user_signed_in?
      SubscriptionMailer.unsubscribe_notification(@subscription).deliver_now
    end
    redirect_to root_path, notice: t('subscriptions.unsubscribe.success')
  end

  def confirm
    @subscription = Subscription.find_by(confirmation_token: params[:confirmation_token])
    @subscription or return redirect_to root_path, flash: { error: t('subscriptions.activation.bad_token') }
    @subscription.confirm!
    redirect_to root_path, notice: t('subscriptions.activation.success')
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def subscription_params
    params[:subscription].permit(:email, :offers, :requests)
  end

  def check_offers_or_requests
    unless subscription_params[:offers] == 'true' || subscription_params[:requests] == 'true'
      redirect_back(fallback_location: root_path, flash: { error: t('subscriptions.subscribe.nothing_selected')})
    end
  end

end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
  def user_subscribed(user, item_type)
    subscription = Subscription.find_by_email(user.email) or return false
    case item_type
      when :requests
        return subscription.requests
      when :offers
        return subscription.offers
      else
        return false
    end
  end
end

app/views/subscriptions/_button.html.erb
<% if user_signed_in? %>
  <% if user_subscribed(current_user, item_type) %>

    <%= custom_bootstrap_form_for(Subscription.new, as: :subscription, url: subscriptions_unsubscribe_user_path, method: :delete, layout: :inline, html: { class: 'one-button-form' }) do |f| %>
      <%= f.hidden_field item_type, value: true %>
      <button class="btn btn-default subscribed-button" id="subscribed-button">
        <span class="subscribed-button-content"><i class='fa fa-check'></i> <%= t('subscriptions.subscribed') %></span>
        <span class="subscribed-button-content" style="display:none;"><i class='fa fa-times'></i> <%= t('subscriptions.actions.unsubscribe') %></span>
      </button>
    <% end %>
  <% else %>
    <%= custom_bootstrap_form_for(Subscription.new, as: :subscription, url: subscriptions_create_path, layout: :inline, html: { class: 'one-button-form' }) do |f| %>
      <%= f.hidden_field item_type, value: true %>
      <%= f.hidden_field :email,
                         value: current_user.email %>
      <button class="btn btn-default" id="subscribe-button">
        <%= t('subscriptions.actions.subscribe') %>
      </button>
    <% end %>
  <% end %>
<% else %>
  <button class="btn btn-default subscription-toggle-button" data-item-type="<%= item_type %>"><%= t 'subscriptions.actions.subscribe' %></button>
<% end %>

app/views/subscriptions/_form.html.erb
<%= custom_bootstrap_form_for(Subscription.new, as: :subscription, url: subscriptions_create_path, layout: :inline, html: {id: "new_subscription_#{item_type}"}) do |f| %>
  <%= f.hidden_field item_type, value: true %>
  <%= f.email_field :email,
                    id: "subscription-email-#{item_type}",
                    placeholder: t('subscriptions.mail'),
                    hide_label: true,
                    class: "subscription-email #{item_type}",
                    data: { :"item-type" => item_type } %>
  <%= f.submit t('subscriptions.actions.subscribe'), class: "btn btn-primary #{item_type} subscription-submit-button", style: 'display: none' %>
  <span class="btn btn-default subscription-toggle-button <%= item_type %>" data-item-type="<%= item_type %>"><%= t('helpers.links.back') %></span>
<% end %>

app/views/subscriptions/sign_off.html.erb
<%= bootstrap_form_for @subscription, layout: :horizontal, url: subscriptions_destroy_path, method: :delete do |f| %>
  <%= f.email_field :email, value: @subscription.email, label: t('helpers.mail') %>

  <%= f.hidden_field :offers %>
  <%= f.hidden_field :requests %>
<% end %>

app/views/subscriptions/sign_up.html.erb
<%= bootstrap_form_for @subscription, layout: :horizontal, url: subscriptions_create_path do |f| %>
  <%= f.email_field :email, value: user_signed_in? ? current_user.email : '', label: t('helpers.mail') %>

  <%= f.hidden_field :offers %>
  <%= f.hidden_field :requests %>
<% end %>