config/routes.rb
Rails.application.routes.draw do

  get 'stats/counts' => 'stats#counts'
  get 'stats/statistiken' => 'stats#statistics'

  post 'subscriptions/create'
  delete 'subscriptions/destroy'
  get 'subscription/confirm/:confirmation_token' => 'subscriptions#confirm', as: 'subscriptions_confirm'
  get 'subscription/unsubscribe/:item_type/:unsubscribe_token' => 'subscriptions#destroy', as: 'subscriptions_unsubscribe'
  delete 'subscription/unsubscribe' => 'subscriptions#unsubscribe_user', as: 'subscriptions_unsubscribe_user'

  get 'users/items'

  get 'reactivate/:token' => 'item_reactivation#reactivate', as: 'reactivate'

  get 'welcome/index'
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => {confirmations: 'confirmations'}

  resources :offers do
    member do
      put :toggle_active
    end
  end

  resources :requests do
    member do
      put :toggle_active
    end
  end

  resources :answers, only: [:create]

  # Error handling
  get '/404' => redirect('/errors/404')
  get '/422' => redirect('/errors/422')
  get '/500' => redirect('/errors/500')
  get '/errors/:error_code', to: 'errors#error'

  root to: 'welcome#index'
end

app/models/offer.rb
class Offer < ApplicationRecord
  include Item

  validates_presence_of :title, :description, :from_date, :rent, :size, :gender, :street, :zip_code
  validates_length_of :title, maximum: 140

  enum gender: { dontcare: 0, female: 1, male: 2 }
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_editable_offer, only: [:edit, :update, :destroy, :toggle_active]

  def index
    @offers = Offer.visible_for(current_user, Offer) #.order(from_date: :asc, updated_at: :desc).includes(:user)
  end

  def show
    @offer = Offer.visible_for(current_user, Offer).find_by(id: params[:id]) or (authenticate_user! and redirect_to offers_path)
  end

  def new
    @offer = Offer.new
  end

  def edit
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.user = current_user

    if @offer.save
      flash = {}
      if current_user.unlocked
        flash[:notice] = tm 'helpers.creation_success', @offer
        Subscription.offers.confirmed.each do |subscriber|
          SubscriptionMailer.new_item_notification(@offer, subscriber).deliver_now
        end
      else
        flash[:alert] = tm 'helpers.creation_success_unlock_required', @offer
        User.admin.find_each do |admin|
          UserMailer.admin_notice_mail(@offer, admin).deliver_now
        end
      end
      redirect_to @offer, flash: flash
    else
      render action: 'new'
    end
  end

  def update
    if @offer.update(offer_params)
      redirect_to @offer, notice: tm('helpers.update_success', @offer)
    else
      render action: 'edit'
    end
  end

  def destroy
    @offer.destroy
    redirect_to offers_url
  end

  def toggle_active
    if @offer.toggle!(:is_public)
      if @offer.is_public?
        notice = tm('helpers.make_public_success', @offer)
      else
        notice = tm('helpers.hide_success', @offer)
      end
      redirect_to @offer, notice: notice
    else
      render action: 'show'
    end
  end

  private
    def set_editable_offer
      @offer = current_user.offers.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      params[:offer].permit(:title, :description, :rent, :size, :gender, :from_date, :to_date, :district, :street, :zip_code)
    end
end

app/helpers/offers_helper.rb
module OffersHelper
  def date_info offer
    out = t('offers.show.from') << ' ' << l(offer.from_date)
    out << ' ' << t('offers.show.to') << ' ' << l(offer.to_date) if offer.to_date
    out
  end

  def address_info offer
    if offer.district && offer.district != ''
      "#{offer.district}, #{offer.street}"
    else
      offer.street
    end
  end
end

app/views/offers/_form.html.erb
<%= custom_bootstrap_form_for @offer do |f| %>
    <div class="edit container-fluid">

      <div class="row">
        <%= f.text_area :title,
                        input_group_wrapper_class: 'input-group-lg col-md-12',
                        wrapper_class: 'title',
                        class: 'short-description',
                        append: (@offer.title ? 140 - @offer.title.length : 140).to_s,
                        placeholder: tm('items.placeholder.title', Offer),
                        hide_label: true %>
      </div>

      <hr/>

      <div class="row">
        <div class="col-md-8">
          <%= f.text_area :description, wrapper_class: 'description', hide_label: true, placeholder: t('items.placeholder.description'), help: ('<span class="warning"><i class="fa fa-shield"></i> ' + tm('privacy.warning', Offer, count: 2) + '</span>').html_safe %>
        </div>

        <div class="col-md-4">
          <div class="info">
            <div class="btn-group input-group input-group-sm gender">
              <span class="input-group-addon"><%= t('offers.help.gender_selection') %></span>
              <%= gender_select @offer.gender %>
              <%= f.hidden_field :gender %>
            </div>

            <%= f.text_field :rent,
                             placeholder: t('activerecord.attributes.offer.rent'),
                             wrapper_class: 'rent',
                             input_group_wrapper_class: 'input-group-sm',
                             prepend: '<i class="fa fa-eur"></i>'.html_safe,
                             hide_label: true %>
            <%= f.text_field :size,
                             placeholder: t('activerecord.attributes.offer.size'),
                             wrapper_class: 'size',
                             input_group_wrapper_class: 'input-group-sm',
                             prepend: 'm²',
                             hide_label: true %>
          </div>

          <div class="date">
            <%= f.localized_text_field :from_date,
                                       'data-behaviour' => 'datepicker',
                                       input_group_wrapper_class: 'input-group-sm',
                                       prepend: t('activerecord.attributes.offer.from_date'),
                                       hide_label: true %>
            <%= f.localized_text_field :to_date,
                                       'data-behaviour' => 'datepicker',
                                       input_group_wrapper_class: 'input-group-sm',
                                       prepend: t('activerecord.attributes.offer.to_date'),
                                       placeholder: t('items.placeholder.temporal'),
                                       hide_label: true %>
          </div>

          <div class="location">
            <%= f.text_field :street,
                             hide_label: true,
                             placeholder: t('activerecord.attributes.offer.street'),
                             class: 'input-sm' %>
            <%= f.text_field :zip_code,
                             hide_label: true,
                             placeholder: t('activerecord.attributes.offer.zip_code'),
                             class: 'input-sm' %>
            <%= f.select :district,
                         grouped_options_for_select([["Der Westen", [
                             "Daxlanden",
                             "Grünwinkel",
                             "Mühlburg",
                             "Oberreut",
                             "Weststadt",
                         ]],
                         ["Die Innenstadt", ["Innenstadt"]],
                         ["Der Osten", [
                             "Durlach",
                             "Grötzingen",
                             "Hagsfeld",
                             "Oststadt",
                             "Rintheim",
                         ]],
                         ["Der Norden", [
                             "Knielingen",
                             "Neureut",
                             "Nordstadt",
                             "Nordweststadt",
                             "Waldstadt",
                         ]],
                         ["Der Süden", [
                             "Beiertheim-Bulach",
                             "Rüppurr",
                             "Südstadt",
                             "Südweststadt",
                             "Weiherfeld-Dammerstock",
                         ]],
                         ["Die Bergdörfer", [
                             "Grünwettersbach",
                             "Hohenwettersbach",
                             "Stupferich",
                             "Palmbach",
                             "Wolfartsweier",
                         ]]], @offer.district),
                         { placeholder: t('activerecord.attributes.offer.district'),
                           hide_label: true,
                           include_blank: true },
                        class: 'input-sm select2',
                        'data-placeholder' => t('activerecord.attributes.offer.district') %>
          </div>
        </div>
      </div>

      <hr/>

      <div class="row">
        <div class="col-md-1 explanation">
          <i class="fa fa-info icon"></i>
        </div>
        <div class="col-md-11">
          <%= tm 'privacy.explanation', @offer %>
        </div>
      </div>

      <hr/>

      <div class="row">
        <div class="col-md-12">
          <div class="form-actions">
            <%= f.submit nil, class: 'btn btn-primary' %>
            <%= link_to t('helpers.links.cancel'), offers_path, class: 'btn btn-default' %>
          </div>
        </div>
      </div>

    </div>

<% end %>

app/views/offers/_list.html.erb
<% if offers.count == 0 %>
  <div>
    <%= t 'offers.list.none' %>
  </div>
<% end %>
<% offers.each do |offer| %>
    <fieldset class="item sort-item" data-rent="<%= offer.rent %>" data-size="<%= offer.size %>" data-from-date="<%= offer.from_date.to_time.to_i %>" data-updated-at="<%= offer.updated_at.to_i %>">
      <%= badges_for offer %>

      <div class="title">
        <strong><%= link_to offer.title, offer %></strong>
      </div>

      <table class="offer-specifics">
        <tbody>
        <tr>
          <td class="icon">
          </td>
          <td class="info">
            <%= gender_icon offer.gender %>
          </td>
          <td class="icon">
            <i class="fa fa-eur"></i>
          </td>
          <td class="info">
            <%= offer.rent %>
          </td>
        </tr>
        <tr>
          <td class="icon">
            <i class="fa fa-square-o"></i>
          </td>
          <td class="info">
            <%= offer.size %>m²
          </td>
          <td class="icon">
            <i class="fa fa-long-arrow-right"></i>
          </td>
          <td class="info">
            <%= date_info offer %>
          </td>
        </tr>
        <tr>
          <td class="icon">
            <i class="fa fa-home"></i>
          </td>
          <td class="info" colspan="3">
            <%= address_info offer %>
          </td>
        </tr>
        </tbody>
      </table>

      <div class="description">
        <div class="short transition"></div>
        <div class="long transition"><%= auto_link simple_format(offer.description) %></div>
      </div>

      <div class="contact">
        <div class="inline-button toggle-collapse">
          <div class="short"><%= t 'helpers.more' %>&#x25BC;</div>
          <div class="long"><%= t 'helpers.less' %>&#x25B2;</div>
        </div>

        <div class="inline-button answer">
          <%= link_to offer do %>
            <%= t("helpers.#{current_user == offer.user ? 'show' : 'answer'}") %>
          <% end %>
        </div>
        <span>&nbsp;|&nbsp;<%= t("offers.show.user", name: offer.user.name) %></span>
      </div>
    </fieldset>
<% end %>

app/views/offers/edit.html.erb
<div class="page-header">
  <h1><%=t '.title' %></h1>
</div>
<%= render partial: 'form' %>

app/views/offers/index.html.erb
<%= render partial: 'shared/list_page_header', locals: { count: @offers.count, item: 'offer', header_class: 'page-header'} %>
<% if @offers.count > 2 %>
  <div class="row">
    <div class="dropdown pull-right" id="sort-button">
      <%= render 'shared/sort_menu' %>
    </div>
  </div>
<% end %>
<div class="row">
  <div class="sort">
    <%= render partial: 'list', locals: { offers: @offers } %>
  </div>
</div>

app/views/offers/new.html.erb
<div class="page-header">
  <h1><%=t ".title" %></h1>
</div>
<%= render partial: 'form' %>

app/views/offers/show.html.erb
<div class="page-header">
  <h1>
    <% if @offer.user == current_user %>
      <%=t '.title.mine' %>
    <% else %>
      <%=t '.title.other', name: @offer.user.name %>
    <% end %>
    <% if current_user&.admin? %>
      <% unless @offer.user.unlocked? %>
        <%= link_to t('users.lock.unlock'), unlock_admin_user_path(@offer.user), method: :put, class: 'btn btn-default' %>
      <% end %>
    <% end %>
  </h1>
</div>

<div class="item">

  <%= badges_for @offer %>
  <div class="title"><strong><%= @offer.title %></strong></div>

  <div class="until">
    <table class="offer-specifics">
      <tbody>
      <tr>
        <td class="icon">
        </td>
        <td class="info">
          <%= gender_icon @offer.gender %>
        </td>
        <td class="icon">
          <i class="fa fa-eur"></i>
        </td>
        <td class="info">
          <%= @offer.rent %>
        </td>
      </tr>
      <tr>
        <td class="icon">
          <i class="fa fa-square-o"></i>
        </td>
        <td class="info">
          <%= @offer.size %>m²
        </td>
        <td class="icon">
          <i class="fa fa-long-arrow-right"></i>
        </td>
        <td class="info">
          <%= date_info @offer %>
        </td>
      </tr>
      <tr>
        <td class="icon">
          <i class="fa fa-home"></i>
        </td>
        <td class="info" colspan="4">
          <%= address_info @offer %>
        </td>
      </tr>
      </tbody>
    </table>
  </div>

  <div class="description">
    <%= auto_link simple_format(@offer.description) %>
  </div>

  <% if current_user != @offer.user %>
    <%= render 'answers/form', answer: @answer ||= @offer.answers.build %>
  <% else %>
    <h2><i class="fa fa-comments-o"></i> <%= t 'answers.title' %></h2>
    <% if @offer.answers.count > 0 %>
      <%= render @offer.answers %>
    <% else %>
      <h4><%= t 'answers.none' %></h4>
    <% end %>
  <% end %>
</div>

<hr />

<div class="form-actions">
  <%= link_to t('helpers.links.back'), offers_path, class: 'btn btn-default' %>
  <% if current_user == @offer.user %>
    <% if @offer.outdated? %>
      <%= link_to t('items.reactivate'), reactivate_path(@offer.get_or_create_reactivator.token), class: 'btn btn-primary' %>
    <% end %>
    <%= link_to t('helpers.links.edit'), edit_offer_path(@offer), class: 'btn btn-default' %>
    <% if @offer.is_public? %>
      <%= link_to '<i class="fa fa-eye-slash"></i> '.html_safe + t('helpers.links.hide'), toggle_active_offer_path(@offer), method: :put, class: 'btn btn-default' %>
    <% else %>
      <%= link_to '<i class="fa fa-eye"></i> '.html_safe + t('helpers.links.make_public'), toggle_active_offer_path(@offer), method: :put, class: 'btn btn-default' %>
    <% end %>
    <%= link_to t('helpers.links.destroy'),
                offer_path(@offer),
                method: 'delete',
                data: { confirm: t('helpers.links.confirm') },
                class: 'btn btn-danger' %>
  <% end %>
</div>