config/routes.rb
Rails.application.routes.draw do

  get 'stats/counts' => 'stats#counts'
  get 'stats/statistiken' => 'stats#statistics'

  post 'subscriptions/create'
  delete 'subscriptions/destroy'
  get 'subscription/confirm/:confirmation_token' => 'subscriptions#confirm', as: 'subscriptions_confirm'
  get 'subscription/unsubscribe/:item_type/:unsubscribe_token' => 'subscriptions#destroy', as: 'subscriptions_unsubscribe'
  delete 'subscription/unsubscribe' => 'subscriptions#unsubscribe_user', as: 'subscriptions_unsubscribe_user'

  get 'users/items'

  get 'reactivate/:token' => 'item_reactivation#reactivate', as: 'reactivate'

  get 'welcome/index'
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => {confirmations: 'confirmations'}

  resources :offers do
    member do
      put :toggle_active
    end
  end

  resources :requests do
    member do
      put :toggle_active
    end
  end

  resources :answers, only: [:create]

  # Error handling
  get '/404' => redirect('/errors/404')
  get '/422' => redirect('/errors/422')
  get '/500' => redirect('/errors/500')
  get '/errors/:error_code', to: 'errors#error'

  root to: 'welcome#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kaheim</title>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= favicon_link_tag 'logo-inverted.png' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<div id="wrap">
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">

      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#kaheim-navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_path, class: 'navbar-brand' do %>
          <%= image_tag 'banner-faecher.png', id: 'banner', alt: 'Kaheim' %>
        <% end %>
      </div>


      <div class="collapse navbar-collapse" id="kaheim-navbar-collapse">

        <ul class="nav navbar-nav">
          <div class="btn-group">
            <%= link_to '/#offers', class: 'btn btn-default navbar-btn' do %>
                <span class="badge badge-info"><%= (c = Offer.visible_for(current_user, Offer).count) > 0 ? c : '' %></span>
                <%= Offer.model_name.human count: c %>
            <% end %>
          </div>
          <div class="btn-group">
            <%= link_to '/#requests', class: 'btn btn-default navbar-btn' do %>
                <span class="badge badge-info"><%= (c = Request.visible_for(current_user, Request).count) > 0 ? c : '' %></span>
                <%= Request.model_name.human count: c %>
            <% end %>
          </div>
        </ul>

        <ul class="nav navbar-nav navbar-right">


          <li id="locale-selection" data-current-locale="<%= I18n.locale %>">
            <% if I18n.locale == :de %>
              <%= link_to url_for(locale: :en), class: 'locale_img' do %>
                <%= image_tag 'de.png', alt: t('helpers.switch_to_english') %>
              <% end %>
            <% else %>
              <%= link_to url_for(locale: :de), class: 'locale_img' do %>
                <%= image_tag 'en.png', alt: t('helpers.switch_to_german') %>
              <% end %>
            <% end %>
          </li>
          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user.email %>
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <% if current_user.admin %>
                  <li><%= link_to 'Admin', '/admin' %></li>
                <% end %>
                <li>
                  <%= link_to t('users.items.title'), users_items_path %>
                </li>
                <li>
                  <%= link_to t('helpers.links.edit_user'), edit_user_registration_path %>

                </li>
                <li>
                  <%= link_to t('helpers.links.sign_out'), destroy_user_session_path, method: :delete %>
                </li>
              </ul>
            </li>
          <% else %>
            <li class="dropdown">
              <a class="dropdown-toggle" href="#" data-toggle="dropdown"><%= t('helpers.links.sign_in') %><strong class="caret"></strong></a>
              <div class="dropdown-menu" style="padding: 15px; width: 300px;">
                <%= render partial: 'devise/sessions/new' %>
                <%= link_to t('helpers.links.sign_up'), new_user_session_path %>
              </div>
            </li>
          <% end %>
        </ul>

      </div>

    </div>
  </nav>

  <div class="container-fluid clear-top" id="main">
    <div class="col-md-12">
      <!--<div class="row">-->
        <% { error: 'danger', alert: 'warning', notice: 'success', info: 'info' }.each do |k, v| %>
          <% if flash[k] %>
            <div class="alert alert-<%= v %> alert-dismissible" role="alert">
              <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
              <div id="flash_<%= k %>">
                <%= flash[k] %>
              </div>
            </div>
          <% end %>
        <% end %>
      <!--</div>-->
      <%= yield %>
    </div>
  </div>
</div>

<%= image_tag 'backdrop.svg', id: 'backdrop' %>

<footer class="footer">
  <div class="container">
    <div class="groups">
      <%= link_to 'https://feg-karlsruhe.de/web/de/angebote/junge-erwachsene', target: 'blank', class: 'group-logo' do %>
        <%= image_tag 'logos/mittendrin_bw.png', alt: 'mittendrin' %>
        <%= image_tag 'logos/mittendrin.png', alt: 'mittendrin', style: 'display: none;' %>
      <% end %>
      <%= link_to 'http://www.sfc-karlsruhe.de', target: 'blank', class: 'group-logo' do %>
        <%= image_tag 'logos/sfc_bw.png', alt: 'SfC-Karlsruhe' %>
        <%= image_tag 'logos/sfc.png', alt: 'SfC-Karlsruhe', style: 'display: none;' %>
      <% end %>
      <%= link_to 'https://www.smd-karlsruhe.de', target: 'blank', class: 'group-logo' do %>
        <%= image_tag 'logos/SMD-Logo_bw.png', alt: 'SMD-Karlsruhe' %>
        <%= image_tag 'logos/SMD-Logo.png', alt: 'SMD-Karlsruhe', style: 'display: none;' %>
      <% end %>
      <%= link_to 'http://www.ac-karlsruhe.de', target: 'blank', class: 'group-logo' do %>
        <%= image_tag 'logos/AC_Logo_bw.png', alt: 'AC-Karlsruhe' %>
        <%= image_tag 'logos/AC_Logo.png', alt: 'AC-Karlsruhe', style: 'display: none;' %>
      <% end %>
    </div>
    <p><%= link_to t('helpers.kaheim'), page_path('kaheim') %> | <%= link_to t('helpers.about'), page_path('about') %></p>
  </div>
</footer>

</body>
</html>